version: '3.8'
services:
  user-db:
    image: postgres
    container_name: user-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_service
    ports:
      - "5432:5432"
    volumes:
      - user-data:/var/lib/postgresql/data
    networks:
      - rede-compartilhada

  user-service:
    build: .
    container_name: user-service
    restart: always
    depends_on:
      - user-db
    ports:
      - "5032:5032"
    volumes:
      - .:/app
    networks:
      - rede-compartilhada
    environment:
      - NODE_ENV=test
      - DB_HOST=user-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=user_service

volumes:
  user-data:

networks:
  rede-compartilhada:
    driver: bridge
